custom_logo_url: "https://www.nasertic.es/es"
custom_logo_title: "Nasertic - Navarra de Servicios y Tecnologias"
report_header_info:
  - Contact E-mail: "secuenciacion@nasertic.es"
  - Application Type: "Nextflow Demultiplex: BCLconvert, fastp, Falco, Contamination"
  - Project Type: "Application"
  - Sequencing Platform: "NovaSeq6000"
module_order:
  - general_stats
  - bcl2fastq
  - bcl_convert
  - fastqc
  - fastp
  - fastq_screen
  - kraken
  - braken
  - nf-core_demultiplex_workflow_summary
  - nf-core_demultiplex_software_versions
  - nf-core_demultiplex_methods_description
  - software_versions
